# Generated by Django 6.0.3 on 2026-03-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Tecnologias',
            new_name='technologies',
        ),
    ]
